/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s.o.puebla;

/**
 *
 * @author Jose
 */
public class Screen3_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main3
     */
    public Screen3_Menu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 125, 125));
        //Establecer el color de fondo a uno rojo.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        Button_Clubs = new javax.swing.JButton();
        Screen_Volunteer = new javax.swing.JButton();
        Screen_Sports = new javax.swing.JButton();
        Screen_Calendar = new javax.swing.JButton();
        Screen_Family = new javax.swing.JButton();
        Screen_Athletes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BCerrar = new javax.swing.JButton();

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        Button_Clubs.setBackground(new java.awt.Color(255, 255, 255));
        Button_Clubs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Clubs_icon.png"))); // NOI18N
        Button_Clubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ClubsActionPerformed(evt);
            }
        });

        Screen_Volunteer.setBackground(new java.awt.Color(255, 255, 255));
        Screen_Volunteer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Volunteer_icon.png"))); // NOI18N
        Screen_Volunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Screen_VolunteerActionPerformed(evt);
            }
        });

        Screen_Sports.setBackground(new java.awt.Color(255, 255, 255));
        Screen_Sports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Sports_icon.png"))); // NOI18N
        Screen_Sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Screen_SportsActionPerformed(evt);
            }
        });

        Screen_Calendar.setBackground(new java.awt.Color(255, 255, 255));
        Screen_Calendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Calendar_icon.png"))); // NOI18N
        Screen_Calendar.setAutoscrolls(true);
        Screen_Calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Screen_CalendarActionPerformed(evt);
            }
        });

        Screen_Family.setBackground(new java.awt.Color(255, 255, 255));
        Screen_Family.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Family_icon.png"))); // NOI18N
        Screen_Family.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Screen_FamilyActionPerformed(evt);
            }
        });

        Screen_Athletes.setBackground(new java.awt.Color(255, 255, 255));
        Screen_Athletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/o/images/Athletes_icon.png"))); // NOI18N
        Screen_Athletes.setMaximumSize(new java.awt.Dimension(75, 75));
        Screen_Athletes.setMinimumSize(new java.awt.Dimension(75, 75));
        Screen_Athletes.setPreferredSize(new java.awt.Dimension(75, 75));
        Screen_Athletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Screen_AthletesActionPerformed(evt);
            }
        });

        jLabel1.setText("Clubs");

        jLabel2.setText("Voluntariado");

        jLabel3.setText("Deportes");

        jLabel4.setText("Calendario");

        jLabel5.setText("Familia");

        jLabel6.setText("Atletas");

        jLabel7.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        jLabel7.setText("Special Olympics Puebla");

        BCerrar.setText("Cerrar sesión");
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Clubs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Screen_Volunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Screen_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Screen_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Screen_Family, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Screen_Athletes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(15, 15, 15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(BCerrar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Screen_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Screen_Volunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Clubs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Screen_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Screen_Family, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Screen_Athletes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(BCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ClubsActionPerformed
        // Abrir ventana de Clubs. 
        Screen4_Clubs Ventana;
            Ventana=new Screen4_Clubs();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Button_ClubsActionPerformed

    private void Screen_VolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Screen_VolunteerActionPerformed
        // Abrir ventana de Voluntariado.
        Screen5_Volunteer Ventana;
            Ventana=new Screen5_Volunteer();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Screen_VolunteerActionPerformed

    private void Screen_SportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Screen_SportsActionPerformed
        // Abrir ventana de Deportes. 
        Screen6_Sports Ventana;
            Ventana=new Screen6_Sports();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Screen_SportsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Abrir ventana de Menu.
        Screen3_Menu Ventana;
            Ventana=new Screen3_Menu();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Screen_CalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Screen_CalendarActionPerformed
        // Abrir ventana de Calendario
        Screen7_Calendar Ventana;
            Ventana=new Screen7_Calendar();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Screen_CalendarActionPerformed

    private void Screen_FamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Screen_FamilyActionPerformed
        // Abrir ventana de Familia
        Screen8_Family Ventana;
            Ventana=new Screen8_Family();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Screen_FamilyActionPerformed

    private void Screen_AthletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Screen_AthletesActionPerformed
        // Abrir ventana de Atletas
        Screen9_Athletes Ventana;
            Ventana=new Screen9_Athletes();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_Screen_AthletesActionPerformed

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        // TODO add your handling code here:
        Screen1_Login Ventana;
            Ventana=new Screen1_Login();
            Ventana.setVisible(true);
            dispose();
    }//GEN-LAST:event_BCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen3_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton Button_Clubs;
    private javax.swing.JButton Screen_Athletes;
    private javax.swing.JButton Screen_Calendar;
    private javax.swing.JButton Screen_Family;
    private javax.swing.JButton Screen_Sports;
    private javax.swing.JButton Screen_Volunteer;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
